blank_issues_enabled: false
contact_links:
  - name: Discussion / Q&A
    url: https://github.com/maxrenke/game-optimizer/discussions
    about: Ask questions and discuss ideas in Discussions rather than Issues.
